/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoCallAppointmentIdRouteImport } from './routes/video-call.$appointmentId'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientMedicalRecordsRouteImport } from './routes/patient.medical-records'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorOverviewRouteImport } from './routes/doctor.overview'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCallAppointmentIdRoute = VideoCallAppointmentIdRouteImport.update({
  id: '/video-call/$appointmentId',
  path: '/video-call/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMedicalRecordsRoute = PatientMedicalRecordsRouteImport.update({
  id: '/patient/medical-records',
  path: '/patient/medical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/doctor/schedule',
  path: '/doctor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorOverviewRoute = DoctorOverviewRouteImport.update({
  id: '/doctor/overview',
  path: '/doctor/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/overview': typeof DoctorOverviewRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/overview': typeof DoctorOverviewRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/overview': typeof DoctorOverviewRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/medical-records': typeof PatientMedicalRecordsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/patients'
    | '/admin/revenue'
    | '/admin/settings'
    | '/book/$doctorId'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/overview'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/dashboard'
    | '/patient/medical-records'
    | '/patient/profile'
    | '/video-call/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/patients'
    | '/admin/revenue'
    | '/admin/settings'
    | '/book/$doctorId'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/overview'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/dashboard'
    | '/patient/medical-records'
    | '/patient/profile'
    | '/video-call/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/register'
    | '/search'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/appointments'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/patients'
    | '/admin/revenue'
    | '/admin/settings'
    | '/book/$doctorId'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/overview'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/doctors/$doctorId'
    | '/patient/appointments'
    | '/patient/dashboard'
    | '/patient/medical-records'
    | '/patient/profile'
    | '/video-call/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorOverviewRoute: typeof DoctorOverviewRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientMedicalRecordsRoute: typeof PatientMedicalRecordsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  VideoCallAppointmentIdRoute: typeof VideoCallAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-call/$appointmentId': {
      id: '/video-call/$appointmentId'
      path: '/video-call/$appointmentId'
      fullPath: '/video-call/$appointmentId'
      preLoaderRoute: typeof VideoCallAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/medical-records': {
      id: '/patient/medical-records'
      path: '/patient/medical-records'
      fullPath: '/patient/medical-records'
      preLoaderRoute: typeof PatientMedicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/overview': {
      id: '/doctor/overview'
      path: '/doctor/overview'
      fullPath: '/doctor/overview'
      preLoaderRoute: typeof DoctorOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorOverviewRoute: DoctorOverviewRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientMedicalRecordsRoute: PatientMedicalRecordsRoute,
  PatientProfileRoute: PatientProfileRoute,
  VideoCallAppointmentIdRoute: VideoCallAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
